-- AlterTable
ALTER TABLE "World" ADD COLUMN "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "World" ADD COLUMN "avatarUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "World" ADD COLUMN "backgroundUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "World" ADD COLUMN "level" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "World" ADD COLUMN "xp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "World" ADD COLUMN "stage" TEXT NOT NULL DEFAULT 'OUTPOST';
ALTER TABLE "World" ADD COLUMN "deletedAt" DATETIME;
